---
# tasks file for roles/common
- include: setup_ssh.yml
  tags: ssh
- include: install_tools.yml
  tags: pkg
- include: firewall.yml
  tags: firewall
- include: docker.yml
  tags: docker
- include: riotfp.yml
  tags: riotfp

# Optional tasks
- include: vim.yml
  when: with_vim

- include: sudoers_nopasswd.yml
  with_items: "{{ server_sudo_nopasswd_users }}"
  loop_control:
    loop_var: nopasswd_user
  when: server_sudo_nopasswd_users is defined
