---
- block:
  - name: Install Vim
    apt:
      pkg: vim
      state: present

  - name: Set Vim as default editor
    alternatives:
      name: "{{ item }}"
      path: /usr/bin/vim.basic
    with_items:
      - editor
      - ex
      - rview
      - rvim
      - vi
      - view
      - vim
      - vimdiff
  become: yes
