---
version: "3"

services:
  broker:
    image: ${DOCKERHUB_REGISTRY}/broker
    container_name: broker
    restart: always
    ports:
      - "8000:8000"
    environment:
      BROKER_HOST: ${SERVER_URI}
      BROKER_PORT: "8000"
      KEY_FILE: "/home/.pyaiot/keys"
    volumes:
      - ${PYAIOT_KEYS}:/home/.pyaiot
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  dashboard:
    image: ${DOCKERHUB_REGISTRY}/dashboard
    container_name: dashboard
    restart: always
    ports:
      - "8080:80"
    environment:
      BROKER_HOST: ${SERVER_URI}
      BROKER_PORT: "8000"
      BROKER_SSL: "False"
      WEB_PORT: "8080"
      MAP_API_KEY: ${SERVER_GOOGLE_API_KEYS}
      KEY_FILE: "/home/.pyaiot/keys"
    volumes:
      - ${PYAIOT_KEYS}:/home/.pyaiot
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
