---
- block:
  - name: Install wireguard
    apt:
      name: wireguard
      state: present
      update_cache: yes

  - name: Generate private keys
    shell: wg genkey
    register: wireguard_genkey
    changed_when: false

  - set_fact:
      private_key: "{{ wireguard_genkey.stdout }}"

  - name: Generate public key
    shell: "echo {{ private_key }} wg pubkey"
    register: wireguard_pubkey
    changed_when: false

  - set_fact:
      public_key: "{{ wireguard_pubkey.stdout }}"

  - set_fact:
      private_ip: "{{ wg_subnet }}.1"

  - name: Create wireguard directory
    file:
      path: /etc/wireguard
      state: directory

  - name: Enable net.ipv4.ip_forward
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      reload: yes
      state: present

  # - name: Allow listen port
  #   ufw:
  #     rule: allow
  #     port: "{{ listen_port }}"
  #     proto: 'udp'

  - name: Configuring wireguard
    template:
      src: wg.conf.j2
      dest: /etc/wireguard/wg0.conf
      owner: root
      group: root
      mode: 600
    notify: wg0_restart
  become: yes
