---
default_user: admin
ansible_python_interpreter: /usr/bin/python3

server_hostname: "riotfp-demo"

# pyaiot default ports
dashboard_port: 8080
broker_port: 8000

ssh_public_keys:
  - ~/.ssh/id_rsa.pub
